os: linux
dist: trusty
language: cpp

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget

env:
  global:
    - BOOST_ROOT=/home/travis/lib/boost
    - RANGE_V3_ROOT=/home/travis/lib/range-v3

script: 
  - cd $TRAVIS_BUILD_DIR
  - /home/travis/lib/bin/b2 toolset=gcc -j2 

matrix:
  include:
    - name: "g++-4.8"
  
    - name: "g++-5"
      install:
        - sudo apt-get install -y g++-5
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
      
    - name: "g++-6"
      install:
        - sudo apt-get install -y g++-6
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6

    - name: "g++-7"
      install:
        - sudo apt-get install -y g++-7
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7

    - name: "g++-8"
      install:
        - sudo apt-get install -y g++-8
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8

before_install:
  - mkdir -p /tmp/deps
  - |
    echo "Installing range-v3"
    cd /tmp/deps
    wget https://github.com/ericniebler/range-v3/archive/0.1.1.tar.gz -O range-v3.tar.gz
    mkdir -p /home/travis/lib/range-v3
    tar xzf range-v3.tar.gz --strip-components=1 -C /home/travis/lib/range-v3
    rm -f range-v3.tar.gz
  - |
    echo "Installing boost"
    cd /tmp/deps
    wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz -O boost.tar.gz
    mkdir -p /home/travis/lib/boost
    tar xzf boost.tar.gz --strip-components=1 -C /home/travis/lib/boost
    rm -f boost.tar.gz
    cd /home/travis/lib/boost/tools/build
    ./bootstrap.sh && ./b2 install --prefix=/home/travis/lib

notifications:
  email: false
